#baseurl: "/front-cover"

# Site settings
name: Sheng Xu
description: "Hope is good thing"
description: "Hope is a good thing"
url: ""


# Delete the lines you don't need
# about 5 elements are recommended
cv_username:  cv_online
pub_list: publications
project_list: projects
blog: blog
others: others


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars.githubusercontent.com/lostagex"


front_img: yes
front_img_path: "imgs/background2.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
